services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRESW_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: formula-grill
    ports:
      - '5432:5432'

  backend:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: node_backend
    environment:
      JWT_SECRET: secret
      # postgres container
      POSTGRES_PRISMA_URL: postgres://postgres:admin@db:5432/formula-grill
      POSTGRES_URL_NON_POOLING: postgres://postgres:admin@db:5432/formula-grill
    ports:
      - '3333:3333'
    depends_on:
      - db
